# Generated by Django 5.2.3 on 2025-10-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('url', models.CharField(max_length=500)),
                ('icon_class', models.CharField(max_length=25)),
            ],
        ),
    ]
