# Generated by Django 5.2.3 on 2025-10-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=25)),
                ('market_url', models.CharField(blank=True, max_length=500)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
    ]
